// <auto-generated />
using CarShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop.Migrations
{
    [DbContext(typeof(CarShopContext))]
    [Migration("20230731205645_View-3")]
    partial class View3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShop.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "red",
                            Manufacturer = "Volvo",
                            Year = 2006
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "red",
                            Manufacturer = "BMW",
                            Year = 2006
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Color = "red",
                            Manufacturer = "Nissan",
                            Year = 2006
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Color = "red",
                            Manufacturer = "MAZ",
                            Year = 2006
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Color = "Blue",
                            Manufacturer = "Toyota",
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Color = "Red",
                            Manufacturer = "Ford",
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Color = "Silver",
                            Manufacturer = "Honda",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("CarShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "None",
                            Name = "Cedan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "None",
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 3,
                            Description = "None",
                            Name = "SVC"
                        });
                });

            modelBuilder.Entity("CarShop.Models.Car", b =>
                {
                    b.HasOne("CarShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarShop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
